name: Verify

on:
  pull_request:

jobs:
  verify-linux-wheels:
    strategy:
      matrix:
        include:
          - identifier: x86_64
            target: x86_64

          - identifier: x86
            target: x86

          - identifier: ARM64
            target: aarch64

    name: Verify - Wheels - Linux - ${{ matrix.identifier }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Build Wheels
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist --find-interpreter
          manylinux: auto
          sccache: "true"
          target: ${{ matrix.target }}
          working-directory: snapr-py

  verify-musl-wheels:
    strategy:
      matrix:
        include:
          - identifier: x86_64
            target: x86_64

          - identifier: x86
            target: x86

          - identifier: ARM64
            target: aarch64

    name: Verify - Wheels - Musl - ${{ matrix.identifier }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Build Wheels
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist --find-interpreter
          manylinux: musllinux_1_2
          sccache: "true"
          target: ${{ matrix.target }}
          working-directory: snapr-py

  verify-windows-wheels:
    strategy:
      matrix:
        include:
          - identifier: x64
            target: x64

          - identifier: x86
            target: x86

    name: Verify - Wheels - Windows - ${{ matrix.identifier }}
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          architecture: ${{ matrix.target }}
          python-version: 3.x

      - name: Build Wheels
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist --find-interpreter
          sccache: "true"
          target: ${{ matrix.target }}
          working-directory: snapr-py

  verify-macos-wheels:
    strategy:
      matrix:
        include:
          - identifier: x86_64
            os: macos-12
            target: x86_64

          - identifier: ARM64
            os: macos-14
            target: aarch64

    name: Verify - Wheels - MacOS - ${{ matrix.identifier }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Build Wheels
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist --find-interpreter
          sccache: "true"
          target: ${{ matrix.target }}
          working-directory: snapr-py

  verify-source-distribution:
    name: Verify - Source Distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Source Distribution
        uses: PyO3/maturin-action@v1
        with:
          args: --out dist
          command: sdist
          working-directory: snapr-py
